version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./dockerConfig/db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nermed
      MYSQL_PASSWORD: nermed123456
    ports:
      - "3306:3306"
  # xampp:
  #   container_name: xampp-container
  #   image: tomsik68/xampp:7.4.27
  #   volumes:
  #     - ~/gestionChantier:/www tomsik68/xampp
  #   ports:
  #     - 41062:80
  #     - 41061:22
  #     - 41063:3306

  # redis:
  #   container_name: redis
  #   image: redis:6-alpine
  #   volumes:
  #     - redis_volume:/data
  #   ports:
  #     - 6379:6379

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - 8088:80

  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8800:80
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080

  gestionchantier:
    container_name: gestionchantier
    # image: backendgestion-gestionchantier:latest
    # restart: always
    depends_on:
      - mysql
      # - redis
      - phpmyadmin
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9230:9229
      # - 8086:8080
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - PMA_HOST=phpmyadmin
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --encore-args="--host ${HOST} --port 8080"

volumes:
  mysql_volume:
  # xampp_volume:
  # redis_volume:
